name: ericemmanuel
favicon: null
layout_spectrum: 0.25556
typography_spectrum: 0.05764
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#8f8073'
    - '#12130f'
    - '#eae6e5'
    - '#8fcb9b'
    - '#496d62'
  brandStrength: 0.6875
  lightness: 0.6875
  saturation: 0.75
  rhythmicContrast: 1
purpose: []
