name: So far beta Grid Sucks
favicon: null
layout_spectrum: 0.99622
typography_spectrum: 0.7768
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: The Journal
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#8f8073'
    - '#12130f'
    - '#eae6e5'
    - '#8fcb9b'
    - '#496d62'
  brandStrength: 0.6875
  lightness: 0.625
  saturation: 0.6875
  rhythmicContrast: 0.75
purpose: []
