layout_spectrum: 0
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
purpose: []
color:
  saturation: 0.75
  brandStrength: 0.6875
  rhythmicContrast: 1
  brandColors:
    - '#8f8073'
    - '#12130f'
    - '#eae6e5'
    - '#8fcb9b'
    - '#496d62'
  lightness: 0.6875
typography_spectrum: 0.08861437
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
name: ericemmanuel
