name: ericemmanuel
favicon: null
layout_spectrum: 0.25556
typography_spectrum: 0.25184
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#0b090a'
    - '#4e4b46'
    - '#cdcfce'
    - '#8398ab'
  brandStrength: 0.6875
  lightness: 0.6875
  saturation: 0.75
  rhythmicContrast: 0.9318992705084383
purpose: []
