name: ericemmanuel
favicon: null
layout_spectrum: 0
typography_spectrum: 0.25184
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.8064495087601244
  lightness: 0.3268056265078485
  saturation: 0.3805338214151561
  rhythmicContrast: 0.9318992705084383
purpose: []
